Homework1
made-ml-in-prod-2021/ulia-demidova pull request #2
Opened 2021-05-05 20:04 UTC by Ulia-Demidova

1. Сырые данные лежат в data/raw/.  Перед обучением модели обработаны категориальные и численные признаки.
2. Конфиги лежат в configs/. Два конфига для обучения: один для логистической регрессии, второй для случайного леса. Один конфиг для предсказаний.
3. Тесты лежат в tests/.
4. Основной код для обучения и предсказания модели: train.py и predict.py соответственно.
5. EDA лежит в notebooks/
6. Оцениваю свою работу в 31 балл, т.к.:
     - ветка homework1 (1 балл)
     - описание к pr (2 балла)
     - выполнение EDA (2 балла)
     - модульная структура (2 балла)
     - логгеры (2 балла)
     - написаны тесты (3 балла)
     - для тестов генерируются синтетические данные (3 балла)
     - конфиги (3 балла)
     - датаклассы для сущностей из конфига (3 балла)
     - сделан и протестирован кастомный трансформер (3 балла)
     - в readme описано, как обучить модель (3 балла)
     - сделан predict, в readme описано как им пользоваться (3 балла)
     - проведена самооценка (1 балл)

2021-05-08 10:01 UTC, ol-ga-00 commented
Файл .gitkeep обычно помещают в пустую директорию, дабы сказать "директорию пустая, но она нам нужна; пусть гит знает о существовании этой директории"
Если в директории помимо .gitkeep есть и другие файлы, то .gitkeep теряет свою актуальность. Прошу удалить такие файлы, где они не актуальны.

2021-05-08 10:03 UTC, ol-ga-00 commented
>    * сделан и протестирован кастомный трансформер (3 балла)

Прошу уточнить, где реализован кастомный трансформер
Требовалось придумать и реализовать его самому
Пример,
https://towardsdatascience.com/pipelines-custom-transformers-in-scikit-learn-the-step-by-step-guide-with-python-code-4a7d9b068156

2021-05-08 10:22 UTC, ol-ga-00 reviewed
Попробовала собрать пакет через команду pip install ml_project/
В итоге в пакете оказались только скрипты директории src/.
На python 3.6 (думаю, что и в других версиях) в пакет попадают только те py файлы, для которых был найден файл ___ init ___.py, по-этому также прошу в директорию tests/ добавить файл ___ init ___.py
И правильнее было бы в директорию src/ положить файлы train.py и predict.py. Таким образом они попадут в пакет и весь код модели будет доступен из src, что удобно.

2021-05-08 10:22 UTC, ol-ga-00 commented on ml_project/src/models/model_predict_eval.py
> +SklearnClassificationModel = Union[RandomForestClassifier, LogisticRegression]
Переменная SklearnClassificationModel встречается в трёх файлах директории src/models/
Предлагаю определить её в одном файле (например, model_fit.py), а в остальных импортировать, чтобы поддерживать значение этой переменной в одном файле, а не в трёх :)

2021-05-08 10:22 UTC, ol-ga-00 commented on ml_project/tests/data/test_make_dataset.py
> +    assert len(train) > len(val)
Слишком абстрактная проверка
Попробуйте проверить, что разделение действительно произошло на 20% и на 80%

2021-05-08 10:22 UTC, ol-ga-00 commented on ml_project/tests/models/test_model_utils.py
> +    assert model.predict(features).shape[0] == target.shape[0]
Думаю, что этот assert бессмысленный!
Функция predict у LogisticRegression всегда вернёт элемент, первая размерность которого будет совпадать с первой размерностью features
А размерности features и target совпадают, иначе бы функция train_model упала на моменте fit

Дополнительно (по желанию) рекомендую в тест модели попробовать добавить проверки, подобные этой https://scikit-learn.org/stable/modules/generated/sklearn.utils.validation.check_is_fitted.html

2021-05-10 18:25 UTC, Ulia-Demidova commented
> > * сделан и протестирован кастомный трансформер (3 балла)
> 
> Прошу уточнить, где реализован кастомный трансформер
> Требовалось придумать и реализовать его самому
> Пример,
> https://towardsdatascience.com/pipelines-custom-transformers-in-scikit-learn-the-step-by-step-guide-with-python-code-4a7d9b068156

Да, не сделала кастомный, неправильно поняла задание. Если не успею его сделать до следующей вашей проверки, то можно без учета этих баллов закрывать. (PS: все остальное вроде поправила)

2021-05-10 20:29 UTC, ol-ga-00 commented
> Да, не сделала кастомный, неправильно поняла задание. Если не успею его сделать до следующей вашей проверки, то можно без учета этих баллов закрывать. (PS: все остальное вроде поправила)

Файл .gitkeep не везде удалён, например, он всё ещё присутствует в src/features/. Но это не критичное замечание, за него снижать баллы не буду.
Все остальные пункты за исключением трансформера поправлены корректно! 
Написание трансформера готова ждать до 17 мая включительно :)

2021-05-11 21:41 UTC, garistvlad requested changes

2021-05-11 21:41 UTC, garistvlad commented on ml_project/src/models/model_fit.py
> +        model = LogisticRegression()
Думаю, из-за того что гиперпараметры моделей задаются здесь, код получается не совсем модульный.
Было бы круто добавить возможность менять гиперпараметры моделей (n_estimators, max_depth, ...) в соответствующих конфигах, которые уже созданы: train_rf_config.yaml  и train_logreg_config.yaml

2021-05-11 21:41 UTC, garistvlad commented on ml_project/src/predict.py
> +
predict.py остался без логирования, в то время как train.py подробно логируем.
Думаю, можно выделить в отдельный модуль, например, функцию setup_logger(), которая бы возвращала настроенный logger, которым можно было бы пользоваться как в train, так и в predict

2021-05-11 21:41 UTC, garistvlad commented on ml_project/src/enities/train_pipeline_params.py
> +import yaml
Мелочный комментарий по импорту не только тут, но и в других файлах.
По PEP8 (https://www.python.org/dev/peps/pep-0008/#imports) импорты делятся на 3 блока:
- сначала идут импорты стандартных библиотек
- потом пакеты, что установлены извне
- в самом конце собственные подключаемые модули, типа srс...

2021-05-11 21:41 UTC, garistvlad commented on ml_project/README.md
> +pytest tests/
Согласен с комментариями предыдущего ревьювера, мне было значительно проще смотреть, когда кто-то уже проверил)
В целом отличная работа!
Добавил некоторые комменты от себя.

2021-05-15 09:19 UTC, ol-ga-00 requested changes
17 мая выставлю оценку

2021-05-20 20:40 UTC, ol-ga-00 approved these changes
Не написан кастомный трансформер
Ставлю 28 баллов

2021-05-20 21:09 UTC, merged